replace forks: chatkit, fresco, popupBubble
nextcloud/talk-android pull request #1205
Opened 2021-04-30 10:08 UTC by mahibi

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

2021-05-02 19:54 UTC, AndyScherzinger commented
@mahibi for popupBubble we could replace it with the original repo/master-snapshot which has the patch too. Or in the midterm solution space replace it by a material button and remove the dependency completely

2021-05-03 21:05 UTC, mahibi commented
libs moved to nextcloud org! PR must be updated to use the libs from there.
for a first step, the exact commit's as before might be used.

2021-05-05 07:08 UTC, nickvergessen requested changes

2021-05-05 07:08 UTC, nickvergessen commented on app/build.gradle
> +    implementation('com.github.mahibi:ChatKit:master-SNAPSHOT', {
```suggestion
    implementation('com.github.nextcloud:ChatKit:master-SNAPSHOT', {
```

2021-05-05 07:08 UTC, nickvergessen commented on app/build.gradle
> +    implementation 'com.github.mahibi.fresco:imagepipeline-okhttp3:111'
```suggestion
    implementation 'com.github.nextcloud.fresco:fresco:111'
    implementation 'com.github.nextcloud.fresco:animated-webp:111'
    implementation 'com.github.nextcloud.fresco:webpsupport:111'
    implementation 'com.github.nextcloud.fresco:animated-gif:111'
    implementation 'com.github.nextcloud.fresco:imagepipeline-okhttp3:111'
```

2021-05-05 07:08 UTC, nickvergessen commented on app/build.gradle
> +    implementation 'com.github.mahibi:PopupBubble:master-SNAPSHOT'
```suggestion
    implementation 'com.github.nextcloud:PopupBubble:master-SNAPSHOT'
```

2021-05-05 10:47 UTC, AndyScherzinger approved these changes
Changes applied, versions fixed, build 🟢 :)

2021-05-05 10:52 UTC, nickvergessen approved these changes

2021-05-05 10:52 UTC, merged