add ability to clear chat history
nextcloud/talk-android pull request #1480
Opened 2021-07-15 13:37 UTC by mahibi

- moderators can clear the chat in the conversations settings
- chat is cleared by system message CLEARED_CHAT

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

2021-07-15 13:44 UTC, mahibi commented
will be rebased etc but must leave for kindergarten now...

2021-07-15 14:27 UTC, splitt3r commented
> 
> 
> will be rebased etc but must leave for kindergarten now...

first things first 👍🏻

2021-07-15 16:13 UTC, nickvergessen requested changes

2021-07-15 16:13 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
> +        return baseUrl + ocsApiVersion + "/apps/spreed/api/v1/chat/" + roomToken;
Hardcoded api version. Please inject it like woth all the other api calls

2021-07-15 16:13 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
> +            ApiUtils.getUrlToClearChatHistory(conversationUser!!.baseUrl, conversationToken)
ApiUtils.getChatApiVersion() is missing before this and should be injected

2021-07-15 16:13 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
> +                            binding.clearConversationHistory.visibility = View.VISIBLE
Needs to be wrapped by a capability check for `clear-history`

Ref https://github.com/nextcloud/spreed/pull/6023

2021-07-15 17:12 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
> +                            }
```suggestion
                            } else {
                                binding.clearConversationHistory.visibility = View.GONE
                            }
```

2021-07-15 17:52 UTC, nickvergessen approved these changes
Works

2021-07-15 18:47 UTC, nickvergessen commented
@timkrueger are you able to test things like this? Or need a crash course?

2021-07-19 11:52 UTC, AndyScherzinger approved these changes

2021-07-19 15:09 UTC, merged