add groups and circles to system messages ("add"+"remove")
nextcloud/talk-android pull request #1851
Opened 2022-03-04 10:16 UTC by mahibi

fix #1848

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

2022-03-04 10:40 UTC, nickvergessen requested changes

2022-03-04 10:40 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
> +                                "circle".equals(individualMap.get("type"))
they should not be prefixed with an `@` and just be replaced normally (like in the web)

2022-03-04 10:40 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
>                          resultMessage = resultMessage?.replace("{$key}", "@" + individualHashMap["name"])
```suggestion
                    if (type == "user" || type == "guest" || type == "call") {
                        resultMessage = resultMessage?.replace("{$key}", "@" + individualHashMap["name"])
```

and instead add a `else` at the end:
```suggestion
                    } else {
                        resultMessage = resultMessage?.replace("{$key}", individualHashMap["name"])
```

2022-03-07 08:39 UTC, nickvergessen approved these changes

2022-03-07 08:39 UTC, nickvergessen commented on app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
> +                if (individualMap != null && individualMap.containsKey("name")) {
Just for the record: type, id and name are not optional. everything else depends on the type.

2022-03-09 09:36 UTC, timkrueger approved these changes

2022-03-09 09:37 UTC, merged