Migrate OperationsMenuController to kotlin
nextcloud/talk-android pull request #1922
Opened 2022-04-17 16:27 UTC by AndyScherzinger

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

2022-04-17 16:40 UTC, AndyScherzinger commented
/backport to stable-14

2022-05-06 13:59 UTC, timkrueger requested changes

2022-05-06 13:59 UTC, timkrueger commented on app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
> +    var ncApi: NcApi? = null
Can this be changed to the following?

```java
    @Inject
    lateinit var ncApi: NcApi
```

2022-05-06 13:59 UTC, timkrueger commented on detekt.yml
> +  maxIssues: 100
I will try to get the `maxIssues` back to 95.

2022-05-06 14:05 UTC, AndyScherzinger commented on app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
> +    var ncApi: NcApi? = null
Yeah, makes sense 👍

2022-05-06 14:17 UTC, timkrueger commented on app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
> +    var ncApi: NcApi? = null
I can do if you not already did.

2022-05-06 15:34 UTC, timkrueger approved these changes

2022-05-07 11:21 UTC, AndyScherzinger commented
/rebase

2022-05-07 11:29 UTC, merged