Feature/1724/missed call notification
nextcloud/talk-android pull request #2415
Opened 2022-09-21 14:26 UTC by mahibi

resolve https://github.com/nextcloud/talk-android/issues/1724

WIP

2022-10-28 14:55 UTC, mahibi commented
detekt checks are not fully satisfied. Some of the checks fail with ComplexMethod. While this is true and should be resolved in general, i suggest to review/merge anyway because this PR already changed a lot and seems stable for me. Further refactoring might take place in follow up PR's (after my vacation or later).

feel free to improve minor things in this PR while reviewing @timkrueger

2022-11-07 11:01 UTC, timkrueger requested changes
The new notifications works as expected. But for the debug information I got a negative delay:

<img width="200" src="https://user-images.githubusercontent.com/606665/200293990-88df0e87-50b2-454e-8fa3-4a71ed15424d.png" />

I'll try to look into it today or tomorrow.

Regarding the detekt issues I'm OK with merging them and resolve them afterwards in a separate PR.

2022-11-10 12:43 UTC, mahibi commented
> The new notifications works as expected. But for the debug information I got a negative delay:

i reverted the calculation of the delivery time. This doesn't make sense because time is not synchronized... in the future we may be able to trigger a test push from the device itself and measure the full roudtrip time until it is received on the device again. But calculating a difference to a timestamp from firebease server doesn't make sense because it's not time-synchronized and never will be.

2022-11-11 11:48 UTC, timkrueger approved these changes

2022-11-11 11:48 UTC, merged