Split call participants and peer connections
nextcloud/talk-android pull request #2600
Opened 2022-11-30 05:57 UTC by danxuliu

Fixes #2544
Requires #2590

It is highly recommended to review this commit by commit rather than all at once ;-) Commit messages may also provide additional context.

Model classes for call participants were added. `CallParticipant` is the main model class, which observes the changes in its peer connections and data channels and updates a data object that keeps track of the state*. This data object is the one exposed to the view classes through a read-only object (`CallParticipantModel`) that can be also observed for changes on specific threads. Thanks to that the `ParticipantDisplayItems` are now automatically updated in the main thread when the model changes, and they also propagate the changes to the adapter (so `notifiyDataSetChanged` is automatically called when any item changed).

In the future it should also listen to signaling messages, for example for raised hands, but also for audio/video enabled/disabled events, as they are also sent through signaling messages besides the data channels just in case the data channel connection could not be established.

Besides that, a helper class is now used to keep track of the participants in the call based on the signaling messages, instead of based on the peer connections. For now it just uses the same signaling messages as before, but in the future this could be used to also handle the message sent by the external signaling server when a participant leaves the room, which implicitly means that the participant left the call (if a participant abruptly leaves the call and the room at the same time no message for leaving the call is sent, only about leaving the room).

With all this now call participants are added and removed when they join and leave the call, and peer connections are only started when the joined participant is publishing media (according to the call flags of the participant for audio/video, and based on the offers received for screen shares). Updating the peer connections of an existing call participant when the flags change during the call is still needed for proper renegotiation support, and it will be done in a follow up.

The steps below should be tested with HPB; without HPB, as the Android app is publishing media, a peer connection is anyway needed to send it to the other participant even if that participant is not publishing.

## How to test

- Start a call without a microphone or camera selected in the browser (that is, not just disabled, but not selected), or without audio and video permissions
- Join the call in the Android app

### Result with this pull request

The Android app does not try to establish a peer connection with the other participant, and no progess bar is shown on that other participant

### Result without this pull request

The Andoid app tries to establish a peer connection with the other participant to receive media (and the external signaling server logs eventually shows that an offer could not be requested), and a progress bar is always shown on that other participant

2022-12-29 19:16 UTC, danxuliu commented
The two new issues reported by SpotBugs are both related to this code:
https://github.com/nextcloud/talk-android/pull/2600/files#diff-50dc4e0167d557f36af93be1eeb64df0cbd347b3a31a4da9d8a2f6a12514b9a5R94-R99

The _Performance - PSC: Presize Collection - Method does not presize the allocation of a collection_ seems to assume that `left` can be initialized to the same size as `knownCallParticipantsNotFound`, because the loop adds the contents from `knownCallParticipantsNotFound` to `left`. However, `left` will not have the same size as `knownCallParticipantsNotFound`, and in most cases it will be much lower, as [the known call participants that are still in the call are removed from `knownCallParticipantsNotFound`](https://github.com/nextcloud/talk-android/pull/2600/files#diff-50dc4e0167d557f36af93be1eeb64df0cbd347b3a31a4da9d8a2f6a12514b9a5R90). Of course `left` could be initialized anyway to the same size as `knownCallParticipantsNotFound`, but in most cases it will just reserve unneeded space, so to fix the performance issue reported by SpotBugs a performance "issue" might be introduced :-) (although in most cases it will be just a few items, so it should not matter much in practice).

The _Dodgy code - UAA: Use Add All - Method uses simple loop to copy contents of one collection to another_ is technically right, but it seems to ignore that the loop does other things with the added elements. Therefore, even if `left.addAll(knownCallParticipantsNotFound)` was used a loop would still need to be used anyway, and I think that the current loop is clearer as it shows in a more cohesive way the changes done to `callParticipant` before adding it to `left` (but, of course, that is just a matter of taste, so also fine by me to change it ;-) ).

2023-01-02 10:52 UTC, mahibi commented
/rebase

2023-01-03 15:17 UTC, mahibi commented
/rebase

2023-01-05 14:04 UTC, mahibi commented
tested with sermo, removed mic and video permissions of caller and also set mic and video to "none" when starting the call.
there is still a progress shown in android..
we can have a look together whenever you want @danxuliu

2023-01-06 10:44 UTC, timkrueger requested changes
Spinning wheel still exists.

2023-01-10 18:00 UTC, mahibi commented
calling from my local machine without hpb with the "none" devices scenario, then the avatar of the android participant is spinning in the webbrowser

2023-01-12 13:46 UTC, mahibi approved these changes

2023-01-12 19:03 UTC, danxuliu commented
> calling from my local machine without hpb with the "none" devices scenario, then the avatar of the android participant is spinning in the webbrowser

Partially fixed (when the session ID of the Android app participant is higher than the session ID of the browser participant, which was a regression introduced in this pull request). When the session ID of the browser participant is the higher one the connection will still fail if the browser participant is not sending media; this was an existing issue and requires further refactorings so, for now, it is not fixed and tracked in https://github.com/nextcloud/talk-android/issues/2679

2023-01-16 09:49 UTC, merged

2023-01-16 09:51 UTC, mahibi commented
/backport to stable-15.1