Open input stream inside the try block
nextcloud/talk-android pull request #2671
Opened 2023-01-09 12:07 UTC by timkrueger

2023-01-10 12:01 UTC, mahibi commented
with this PR, it's now possible to log in with https on my local machine (which fails without this PR), but after login
avatars of the participants are not loaded. in the log there is:

```
E/RealImageLoader: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@224915028@22.49.15 (100400-499306216):25)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
```

This is most probably related to coil.
Probably coil also needs to trust the certificate if the main okhttp client trusts it..

2023-01-10 12:06 UTC, mahibi requested changes
TODO: coil needs to accept the certificate too. Otherwise avatars might not load.

2023-01-10 12:15 UTC, mahibi commented
While testing/debugging this: always remember to delete the app before reinstall it, otherwise the certificate remains!

2023-03-14 16:20 UTC, tobiasKaminsky approved these changes

2023-03-14 16:27 UTC, mahibi commented
/rebase

2023-03-14 18:59 UTC, merged

2023-03-14 18:59 UTC, mahibi commented
/backport to stable-16.0