Replace Controller with Activity for ConversationList
nextcloud/talk-android pull request #2932
Opened 2023-04-06 12:50 UTC by mahibi

this PR replaces controller with Activity, see https://github.com/nextcloud/talk-android/issues/1551

also fix  #2615

### 🚧 TODO

This is the current state before my vacation (i'm back at 17.4.).
There are some minor obvious bugs known UI/theming-wise (fyi @AndyScherzinger if you would like to fix anything)

Other than that i added some workarounds that the app will work with the remaining controllers. 
From my pov everything should work, altough many things can be improved.

Remaining controllers are:
* ServerSelectionController
* WebViewLoginController
* AccountVerificationController
* SwitchAccountController
* LockedController

When the PR has been tested and found to be OK, feel free to merge @AndyScherzinger 

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2023-04-06 12:52 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
> +                    // TODO
todo

2023-04-06 12:52 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
> +                        // TODO
todo

2023-04-06 12:53 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
> +            // TODO
todo! 
Blocker for merging...

2023-04-06 17:41 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
> +// TODO: check what needs to be migrated from this class to BaseActivity etc when conductor is removed
todo. Maybe in follow up PR's..

2023-04-09 10:18 UTC, AndyScherzinger requested changes
Theming is fully broken regarding respecting server-side theming, coloring is always blue atm, needs to be fixed first before merging

2023-04-10 07:26 UTC, AndyScherzinger approved these changes

2023-04-10 07:26 UTC, merged