[WIP] fixing activity transitions
nextcloud/talk-android pull request #3050
Opened 2023-05-24 16:56 UTC by rapterjet2004

Signed-off-by: Julius Linus julius.linus@nextcloud.com

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] get it working
- [ ] get it reviewed

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2023-05-30 12:44 UTC, mahibi commented
Now transitions are the same on all my devices :+1: 
However for me the transitions doesn't feel quite smooth. 
Seems like some views are handled seperately (for example second 7 in the video: the notification settings are already in place and all other elements are animated.)
Other messengers slide the whole screen most of the times which is much nicer in my opinion. Any chance this you could give this a try @rapterjet2004 ?

2023-05-30 17:07 UTC, rapterjet2004 commented
Ok so I got the transitions to work across I believe every screen. It was a small bug with how Slide() requires all views to be set visible at compile time I think. On a side note the views in Conversation Info and Settings use [this library](https://github.com/yarolegovich/MaterialPreferences) which hasn't been updated in 3 years. It seems harmless right now but maybe we should switch to native eventually? The UI looks kinda dated IMO.

2023-05-31 05:53 UTC, AndyScherzinger commented
Yeah, getting rid of material preferences library and just doing it plain native would be desirable 👍

2023-05-31 05:54 UTC, AndyScherzinger commented
Yet that should be handled via a separate PR of course 😊👍

2023-05-31 05:54 UTC, AndyScherzinger approved these changes

2023-05-31 16:50 UTC, rapterjet2004 commented
I did some reading, and experimented a bit with delays and setting start and end animation speeds separately and decided that just setting both to have a transition speed of 50ms instead of the default makes the transition appear a bit less flashy, but perhaps more responsive? I only tried this on my emulator. But I took a video of it here. I'm not sure if it also appears this way on other devices. 

before

https://github.com/nextcloud/talk-android/assets/69230048/c2f37d9a-7bb0-4f10-a1d5-fce6b45d5ba9


after

https://github.com/nextcloud/talk-android/assets/69230048/8a58ac06-2cba-4945-be25-4abbd08ce3e4

Not sure what's causing the conversations to flicker upon the end transition, that's just them refreshing right?

2023-06-01 08:13 UTC, mahibi commented
Thanks for having a look into it @rapterjet2004 
On real devices the behaviour of master still feels better to me.
I suggest we will do the next release without this PR and gain some feedback. So maybe we can have another look at it in the future.
Maybe @AndyScherzinger has an opinion on this?

2023-06-01 08:15 UTC, mahibi requested changes
i suggest to not merge it as it doesn't feel smooth on real devices.
Any other options welcome...

2023-06-05 10:35 UTC, closed without merging