Added Unit Test For UserIdUtils
nextcloud/talk-android pull request #3280
Opened 2023-08-26 21:06 UTC by Smarshal21

**Added Unit Test For UserIdUtils**
### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included 
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2023-08-26 21:08 UTC, Smarshal21 commented
@mahibi @AndyScherzinger  as we had a chat i have started the writing tests by writing a simple unit test
could you ptal and let me know

2023-08-28 07:35 UTC, AndyScherzinger requested changes

2023-08-28 07:35 UTC, AndyScherzinger commented on app/build.gradle
> +    testImplementation 'junit:junit:4.13.2'
`junit` and `mockito` are duplicated, see https://github.com/nextcloud/talk-android/pull/3280/files#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R290 for the original entries and please then move the `mockito-android` dependency down there, so the test dependencies are grouped together.

2023-08-28 07:35 UTC, AndyScherzinger commented on app/src/test/java/com/nextcloud/talk/utils/UserIdUtilsTest.kt
> +package com.nextcloud.talk.utils
Please add the usual license header as a comment, see for example https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt#L1-L21

2023-08-28 07:39 UTC, AndyScherzinger commented
@Smarshal21 I added some minor comments. On top of that it would be nice if you could add a Github action to execute the tests. For inspiartion see https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml while that would need to be rewriten since you won't have jacoco and the comment deletion. So a simple execution should be enough, like a modified version of https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml#L32-L35 with a different, fitting value for https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml#L35

2023-08-28 07:41 UTC, AndyScherzinger commented
Also @Smarshal21 since we added you to the organization you can just create the branches within this repository. This makes your life and ours easier since rebases are a bit simpler and all GH actions will get executes since that is blocked on forks for security reasons.

2023-08-28 09:18 UTC, Smarshal21 commented
> Also @Smarshal21 since we added you to the organization you can just create the branches within this repository. This makes your life and ours easier since rebases are a bit simpler and all GH actions will get executes since that is blocked on forks for security reasons.

Sure

2023-08-29 08:36 UTC, Smarshal21 commented
> > @Smarshal21 I added some minor comments. On top of that it would be nice if you could add a Github action to execute the tests. For inspiartion see https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml while that would need to be rewriten since you won't have jacoco and the comment deletion. So a simple execution should be enough, like a modified version of https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml#L32-L35 with a different, fitting value for https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml#L35
> 
> Yeah Thanks!! Will resolve them

Done

2023-08-29 08:37 UTC, Smarshal21 commented
Done

2023-09-04 13:49 UTC, Smarshal21 commented
> @Smarshal21 I added some minor comments. On top of that it would be nice if you could add a Github action to execute the tests. For inspiartion see https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml while that would need to be rewriten since you won't have jacoco and the comment deletion. So a simple execution should be enough, like a modified version of https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml#L32-L35 with a different, fitting value for https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml#L35

could you tell me more about the github actions??

2023-09-07 16:57 UTC, AndyScherzinger commented
> could you tell me more about the github actions??

@Smarshal21 anything specific besides the referenced workflow files?

2023-09-07 16:57 UTC, AndyScherzinger commented
Sorry for the late reply, very busy these days :/

2023-09-07 17:08 UTC, Smarshal21 commented
> > could you tell me more about the github actions??
> 
> @Smarshal21 anything specific besides the referenced workflow files?

i wanna clarify about what else i have to include in this pr so that i can get an idea to write other tests as well

2023-09-07 17:08 UTC, Smarshal21 commented
> Sorry for the late reply, very busy these days :/

Thats fine :)

2023-09-08 08:58 UTC, merged

2023-09-08 09:05 UTC, mahibi commented
i guess there was some confusion about the suggested github workflow.

The test itself is absolutely fine @Smarshal21 so i merged it.

Adding the github workflow is unrelated. It is about executing all tests on github, see https://docs.github.com/en/actions/using-workflows/triggering-a-workflow for explanation.
i am also not very familiar with it yet so i don't know off the top of my head what exactly is needed from https://github.com/nextcloud/android/blob/master/.github/workflows/unit-tests.yml
e.g. what has to be changed in uploadReport.sh etc..