shows edit message view only when user edits a message
nextcloud/talk-android pull request #3766
Opened 2024-03-26 09:31 UTC by sowjanyakch

Resolves #3765.

The edit message view is only shown when the user edits a message. 

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2024-03-26 10:52 UTC, mahibi commented
/backport to stable-19.0

2024-03-26 10:57 UTC, mahibi approved these changes

2024-03-26 11:08 UTC, mahibi requested changes
this can still show the send button above the microphone button.
![grafik](https://github.com/nextcloud/talk-android/assets/2932790/8394531f-3db2-4995-a8c0-ad3b8cf179ea)

Could you have a look if this also can be fixed?

2024-03-26 11:54 UTC, sowjanyakch commented
Sure. I will fix this issue.

2024-04-03 15:01 UTC, mahibi approved these changes

2024-04-03 15:02 UTC, merged