Contacts activity
nextcloud/talk-android pull request #3936
Opened 2024-05-22 14:16 UTC by sowjanyakch

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2024-07-11 15:09 UTC, rapterjet2004 requested changes
Great Job! 👍🏾 It works on my emulator

Just need to implement
- [ ] Create new public conversation
- [ ] Proper theming

Me and @mahibi are also doing a lot of work on #3952 to get offline conversations + chatting working. I don't think there is much overlap with your PR, but just a heads up in case there are merge conflicts.

2024-07-11 15:09 UTC, rapterjet2004 commented on app/src/main/java/com/nextcloud/talk/contacts/SearchComponent.kt
> +    Surface(
Theme this to match, and the exit cross should only appear once some text as been entered into the text field

2024-07-11 16:00 UTC, rapterjet2004 commented on app/src/main/java/com/nextcloud/talk/contacts/ContactsActivityCompose.kt
> +        setContent {
Do you have any idea how theming will work with compose? Is it a heavy refactoring?

2024-07-12 07:52 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
> +interface NcApiCoroutines {
:+1:

2024-07-12 08:13 UTC, mahibi commented
Great to have a kickoff with jetpack compose :rocket: 
From my side this can be merged once the remarks from Julius are solved and issues/features should be fixed/done in followup PRs.

2024-07-12 08:13 UTC, mahibi commented
One thing i realized when testing are some bugs that existed already before this PR:
1) I have 2 accounts on sermo and with my account "Marcel" i am not able to see the account "marcel2" in the contacts. Maybe i get something wrong but i don't have an idea which could explain why it shouldn't be shown. When i search for it, it appears, but it's not in the list by default.

2) When opening a conversation and go to Conversation info to add participants, the search is broken. When i enter a name, it won't appear in the results list. Then i delete the search and try and, and then more results appear than before.
Bug report is https://github.com/nextcloud/talk-android/issues/2037

2024-07-12 08:14 UTC, mahibi approved these changes

2024-07-15 10:25 UTC, mahibi commented
@sowjanyakch 
Can you rebase on master? Or as the rebase was not done regulary and may be difficult now, you can also merge master into this branch. For future branches please always use rebase and do it regulary.

please also fix warnings from  https://app.codacy.com/gh/nextcloud/talk-android/pull-requests/3936/issues

2024-07-23 11:18 UTC, merged