Lock room
nextcloud/talk-android pull request #4428
Opened 2024-11-08 16:28 UTC by sowjanyakch

Resolve #3664

🏚️ Before | 🏡 After
---|---
B | A

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2024-11-11 14:14 UTC, mahibi requested changes
The message input field must be disabled when a conversation is locked.

update: IIRC it's locked when leaving and opening the chat again. Improvements to this may be related to https://github.com/nextcloud/talk-android/issues/4354 so solving it is out of scope for this PR.

2024-11-14 09:35 UTC, sowjanyakch commented on app/src/main/java/com/nextcloud/talk/api/NcApi.java
> +    Observable<GenericOverall> setConversationReadOnly(@Header("Authorization") String authorization,
This will be implemented in issue #4412.

2024-11-14 15:28 UTC, nickvergessen commented on app/src/main/res/layout/activity_conversation_info.xml
> +            <LinearLayout
Conversation settings sounds good enough for mobile atm

2024-11-14 15:51 UTC, mahibi approved these changes

2024-11-14 15:53 UTC, merged