Fetch messages in background
nextcloud/talk-android pull request #4475
Opened 2024-11-22 16:16 UTC by rapterjet2004

- fixes #4381 

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2024-11-26 21:04 UTC, mahibi commented
not to be merged for 20.1.0, might review only afterwards

2024-12-03 11:34 UTC, mahibi requested changes
something is wrong with the chatBlocks, they don't get merged correctly (i guess because "lastKnown" in the fieldMap is not set up correctly). In the UI this leads to the fact that the newest loaded message is shown first, and then the older messages appear. With correctly merged chatBlocks this should not happen.

There is a high danger to introduce serious bugs when something is wrong with the chatBlocks, so i might be quite nitpicky with this PR ;)

2024-12-03 11:34 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
> +    private fun List<ConversationModel>.refreshMessages() {
As we already have a ConversationListViewModel we should use this, so as the code is just about data handling it should not be in the Activity.

2024-12-03 11:41 UTC, mahibi commented
fyi @rapterjet2004 i rebased on master...

2025-01-20 16:03 UTC, mahibi requested changes

2025-01-21 17:51 UTC, rapterjet2004 commented on app/src/main/java/com/nextcloud/talk/conversationlist/viewmodels/ConversationsListViewModel.kt
> +        chatRepository.setData(model, credentials, urlForChatting)
Dependency Injection is a bit confusing, as even though the provider is annotated as a @Singleton, it's not an actual Singleton. Each time we inject, we create a separate instance. 

Async handling should be fine, the suspend function runs in ViewModelScope, so it shouldn't be attached the activity lifecycle.

2025-01-22 13:44 UTC, mahibi commented
will do some testing tomorrow, then it should be fine to merge

2025-01-23 13:08 UTC, mahibi commented
sorry Julius i won't merge this PR.

There were just too many things wrong when i tested (messages that i expected to be there were missing / Messages were loaded from when conversation was created / ...)

Also the calculation with the previous/current/result lists doesn't make sense to me.
Why is only the difference to the last state counted? If the unread messages are missing, we want to have them all.

Tbh i would like to close the PR for now and we should have a fresh look at it later.

2025-01-23 13:08 UTC, mahibi requested changes
see comment in pr

2025-02-14 19:45 UTC, rapterjet2004 commented
Rewrote and simplified the `updateRoomMessages`, couldn't replicate the other errors. Can you point me in the right direction?

2025-03-06 13:30 UTC, mahibi commented
> Rewrote and simplified the `updateRoomMessages`, couldn't replicate the other errors. Can you point me in the right direction?

hope to find time for this one soon! can you rebase and solve the merge conflicts?

2025-03-19 13:43 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
> +        showErrorDialog()
showErrorDialog is already called in handleHttpExceptions

2025-03-19 14:33 UTC, mahibi requested changes
The current state doesn't work for me because credentials are not set:

```
2025-03-19 15:26:34.201 17596-17874 OfflineFir...Repository com.nextcloud.talk2                  E  Something went wrong when pulling chat messages (attempt: 4)
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property credentials has not been initialized
                                                                                                    	at com.nextcloud.talk.chat.data.network.OfflineFirstChatRepository.getMessagesFromServer(OfflineFirstChatRepository.kt:512)
                                                                                                    	at com.nextcloud.talk.chat.data.network.OfflineFirstChatRepository.sync(OfflineFirstChatRepository.kt:579)
                                                                                                    	at com.nextcloud.talk.chat.data.network.OfflineFirstChatRepository.updateRoomMessages(OfflineFirstChatRepository.kt:313)
```

2025-03-19 14:33 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
> +            lookIntoFuture = true,
lookIntoFuture = true
is wrong. It would trigger the long polling which is not wanted in this case.

2025-03-19 14:33 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/conversationlist/viewmodels/ConversationsListViewModel.kt
> +
Could be simplified to this?:

fun updateRoomMessages(list: List<ConversationModel>) {
    viewModelScope.launch(Dispatchers.IO) {
        list.filter { it.unreadMessages > 0 }
            .forEach { chatRepository.updateRoomMessages(it.internalId, it.unreadMessages) }
    }
}

2026-09-17 15:51 UTC, mahibi commented
replaced by https://github.com/nextcloud/talk-android/pull/6454

2026-09-17 15:51 UTC, closed without merging