Add clear icon for search view in open conversations
nextcloud/talk-android pull request #4497
Opened 2024-11-28 08:50 UTC by sowjanyakch

Resolve #4490

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2024-12-03 13:13 UTC, mahibi requested changes
Could you have a closer look how much work it is to use a SearchView (https://developer.android.com/reference/com/google/android/material/search/SearchView) here? I think it would make more sense as it's intended to use with the appbar.

If SearchView is not possible for whatever reason, then you should wrap the 
TextInputEditText inside a TextInputLayout which will also give you the possibility to use built in cancel button etc.

2024-12-13 11:42 UTC, mahibi requested changes
when typing, the result list should also be updated if there searched string doesn't match anymore.

For example there are 3 rooms called "Talk".
When i search for "Tal", all 3 rooms are shown.
But when i add a letter that doesn't match, the results should disappear. So when i type "Talx", the old results are still shown.

2024-12-13 12:03 UTC, sowjanyakch commented
I will implement the search bug in a different PR.

2024-12-13 12:04 UTC, mahibi approved these changes

2024-12-13 12:04 UTC, merged