Migrating away from java.util.Date to java.time - DateTimePickerFragment
nextcloud/talk-android pull request #4552
Opened 2024-12-17 17:54 UTC by rapterjet2004

#4274

Migrating to java.time would remove so much code in `DateTimePickerFragment` that I figured I might as well also converted the dialog fragment to compose too.

### 🚧 TODO

- [ ] Checking if the timestamp is sent correctly
- [ ] Retrieving the old reminder, prob have to rewrite API functions in composeAPI
- [ ] Delete the old fragment + xml
- [ ] Theming

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

2025-01-03 10:41 UTC, sowjanyakch requested changes
1. I set remainder using custom time and remind me later is always set to 03 Jan, 18:00 pm and it is not updated with the set custom time. 

2.  Set a custom time for remainder, then try to change the time - use one of the predefined options, the remind me later is not updated.

3. Replace hardcoded strings with stringResource()

2025-01-07 18:41 UTC, mahibi requested changes
worked fine for me when testing. Was not able to reproduce the reported issues from Sowjanya.

2025-01-07 18:41 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
> + * SPDX-FileCopyrightText: 2024 Your Name <your@email.com>
insert your name..

2025-01-07 18:41 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
> +    // TODO make an issue out of the problem I gave marcel
?

2025-01-07 18:41 UTC, mahibi commented on app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
> +    // }
can be deleted?

2025-01-09 12:11 UTC, mahibi commented
i'm currently looking into the lint warings regarding the Uyghur(ug) translations so we don't have to merge with red CI

2025-01-10 10:34 UTC, mahibi approved these changes

2025-01-10 10:51 UTC, merged

2025-01-10 10:51 UTC, mahibi commented
won't backport